-- Mise à jour téléphone et email des clients dans la table factures
-- Généré depuis export(11).csv

-- 1. Ajouter la colonne email_client si pas encore fait
ALTER TABLE factures ADD COLUMN IF NOT EXISTS email_client TEXT;

-- 2. Mises à jour par client (utilise le meilleur contact comptable/facturation)

UPDATE factures SET telephone = '0155327274', email_client = 'Ivana.FRKAPETESIC@howdengroup.com' WHERE LOWER(client) = LOWER('267 PRADO');
UPDATE factures SET telephone = '0491016590', email_client = 'compta@4ddemolition.com' WHERE LOWER(client) = LOWER('4D DEMOLITION');
UPDATE factures SET telephone = '0618870870' WHERE LOWER(client) = LOWER('8 MAI PNEUS');
UPDATE factures SET telephone = '0422431592', email_client = 'isabelle.pethy@intradef.gouv.fr' WHERE LOWER(client) = LOWER('A I A  Cuers Pierrefeu');
UPDATE factures SET telephone = '0771278214' WHERE LOWER(client) = LOWER('ABDEL MARCHE AVIGNON');
UPDATE factures SET telephone = '0491594085', email_client = 'contact@afppcd-idf.com' WHERE LOWER(client) = LOWER('AFPPCD');
UPDATE factures SET telephone = '0650672019', email_client = 'a.rizzo@segedia.fr' WHERE LOWER(client) = LOWER('AIELLO CAROLE');
UPDATE factures SET telephone = '0607392403', email_client = 'factures.frs@aismt13.fr' WHERE LOWER(client) = LOWER('AISMT');
UPDATE factures SET telephone = '0628543364' WHERE LOWER(client) = LOWER('AIXIA');
UPDATE factures SET telephone = '0650743503' WHERE LOWER(client) = LOWER('ALG DISTRIBUTION');
UPDATE factures SET telephone = '0768558546' WHERE LOWER(client) = LOWER('ALIMENTATION DAYS & NIGHT');
UPDATE factures SET telephone = '0749074567' WHERE LOWER(client) = LOWER('ALIMENTATION DU PREPAOU');
UPDATE factures SET telephone = '0602712822' WHERE LOWER(client) = LOWER('ALTA CAFE');
UPDATE factures SET telephone = '0674588151' WHERE LOWER(client) = LOWER('AMICALE LYCEE NELSON MANDELA');
UPDATE factures SET email_client = 'contact.amycar@gmail.com' WHERE LOWER(client) = LOWER('AMYCAR');
UPDATE factures SET telephone = '0486643936', email_client = 'apicom.contact@gmail.com' WHERE LOWER(client) = LOWER('API COM');
UPDATE factures SET telephone = '0607760003' WHERE LOWER(client) = LOWER('AU COEUR DU PANIER');
UPDATE factures SET telephone = '0751096184' WHERE LOWER(client) = LOWER('AU PAIN D''AUTREFOIS');
UPDATE factures SET telephone = '0603946933', email_client = 'napoletano.florent@gmail.com' WHERE LOWER(client) = LOWER('AUBADEM');
UPDATE factures SET telephone = '0490907357', email_client = 'fcharpy@gmail.com' WHERE LOWER(client) = LOWER('AUBERGE LA TREILLE');
UPDATE factures SET telephone = '0619840007', email_client = 'rachid.boukada@yahoo.fr' WHERE LOWER(client) = LOWER('AUCHAN ST LOUP');
UPDATE factures SET email_client = 'auto.ecole.des.facultes@orange.fr' WHERE LOWER(client) = LOWER('AUTO ECOLE DES FACULTES');
UPDATE factures SET telephone = '0778122650', email_client = 'speedcar13@hotmail.fr' WHERE LOWER(client) = LOWER('AUTO SPEED');
UPDATE factures SET telephone = '0442105288', email_client = 'david.boutillier@aviapartner.aero' WHERE LOWER(client) = LOWER('AVIAPARTNER');
UPDATE factures SET telephone = '0758843078' WHERE LOWER(client) = LOWER('AYAD PROMO MEDITERRANEE');
UPDATE factures SET telephone = '0650672019', email_client = 'ayellocarole@gmail.com' WHERE LOWER(client) = LOWER('AYELLO Carole');
UPDATE factures SET telephone = '0616912754', email_client = 'laurent.bellaiche13@gmail.com' WHERE LOWER(client) = LOWER('Association ADS - CENTRE MEDICALE');
UPDATE factures SET telephone = '0658240479', email_client = 'c.pingot@bcontact.fr' WHERE LOWER(client) = LOWER('B.CONTACT DEVELOPPEMENT');
UPDATE factures SET telephone = '0614737377', email_client = 'gerard.barthelemy@gedimat.fr' WHERE LOWER(client) = LOWER('BARTHELEMY GEDIMAT');
UPDATE factures SET telephone = '0494229090' WHERE LOWER(client) = LOWER('BEST DRIVE');
UPDATE factures SET email_client = 'contact@betgarnier.fr' WHERE LOWER(client) = LOWER('BET GARNIER');
UPDATE factures SET telephone = '0620454570' WHERE LOWER(client) = LOWER('BILLIA  SYLVAIN');
UPDATE factures SET telephone = '0679561868', email_client = 'QSRFR.AIXComptabilite@grupobimbo.com' WHERE LOWER(client) = LOWER('BIMBO');
UPDATE factures SET telephone = '0629356952' WHERE LOWER(client) = LOWER('BOULANGER L''INAIA');
UPDATE factures SET telephone = '0616559753' WHERE LOWER(client) = LOWER('BOULANGERIE CHEZ EMIR');
UPDATE factures SET telephone = '0773394555' WHERE LOWER(client) = LOWER('BOULANGERIE DES MILLES ET UNE SAVEURS');
UPDATE factures SET telephone = '0744925092', email_client = 'ablp@cabinet-comptable-13.fr' WHERE LOWER(client) = LOWER('BOULANGERIE LA BAGUETTE MAGIQUE');
UPDATE factures SET telephone = '0767225875' WHERE LOWER(client) = LOWER('BOULANGERIE LE COIN CHAUD');
UPDATE factures SET telephone = '0652493293' WHERE LOWER(client) = LOWER('BOULANGERIE LE PORT');
UPDATE factures SET telephone = '0658528749' WHERE LOWER(client) = LOWER('BOULANGERIE SAS JANNAT CASTELLANE');
UPDATE factures SET email_client = 'brunge.louisk@gmail.com' WHERE LOWER(client) = LOWER('BRUNGE CAMOINS');
UPDATE factures SET telephone = '0628764850' WHERE LOWER(client) = LOWER('BURGER AVENUE');
UPDATE factures SET telephone = '0623170115', email_client = 'contact@autocars-burle.com' WHERE LOWER(client) = LOWER('BURLE AUTO');
UPDATE factures SET telephone = '0494616367' WHERE LOWER(client) = LOWER('C.H.I  STE MUSSE');
UPDATE factures SET telephone = '0766085612' WHERE LOWER(client) = LOWER('CAFE DU SOUDAN');
UPDATE factures SET telephone = '0626327468' WHERE LOWER(client) = LOWER('CAFE KAHINA');
UPDATE factures SET telephone = '0774566635' WHERE LOWER(client) = LOWER('CAFE LES KHEIS');
UPDATE factures SET telephone = '0618276714' WHERE LOWER(client) = LOWER('CAFE PLUS');
UPDATE factures SET email_client = 'gamassur@gamassur.com' WHERE LOWER(client) = LOWER('CAMPOU ET FILS (GAMA) assurance');
UPDATE factures SET telephone = '0611149115' WHERE LOWER(client) = LOWER('CARI MED FAYARD');
UPDATE factures SET email_client = 'carreclotures84200@gmail.com' WHERE LOWER(client) = LOWER('CARRE CLOTURES');
UPDATE factures SET telephone = '0660579441', email_client = 'axocar13@gmail.com' WHERE LOWER(client) = LOWER('CARROSSERIE AXOCAR');
UPDATE factures SET telephone = '0632694072' WHERE LOWER(client) = LOWER('CARROSSERIE DE LA POMME');
UPDATE factures SET telephone = '0761940903', email_client = 'manuel.martins@compass-groupe.fr' WHERE LOWER(client) = LOWER('CARSAT');
UPDATE factures SET telephone = '0658388097', email_client = 'secretariat.ccp13@gmail.com' WHERE LOWER(client) = LOWER('CCP13');
UPDATE factures SET telephone = '0494038741', email_client = 'abdelrazac.el-khemiri@transdev.com' WHERE LOWER(client) = LOWER('CE RMTT');
UPDATE factures SET telephone = '0496116301' WHERE LOWER(client) = LOWER('CENTRE DENTAIRE CE');
UPDATE factures SET telephone = '0667144047', email_client = 'christelle.delaporteblanc@ch-pierrefeu.fr>' WHERE LOWER(client) = LOWER('CENTRE HOSPITALIER GUERIN');
UPDATE factures SET telephone = '0617168212', email_client = 't.design.1313@gmail.com' WHERE LOWER(client) = LOWER('CENTRE MEDICAL GIBBES');
UPDATE factures SET telephone = '0442971508', email_client = 'rieu@cerege.fr' WHERE LOWER(client) = LOWER('CEREGE');
UPDATE factures SET telephone = '0783209327', email_client = 'fbennour@iliad-free.fr' WHERE LOWER(client) = LOWER('CERTICALL');
UPDATE factures SET telephone = '0494995142' WHERE LOWER(client) = LOWER('CES JACQUES PREVERT');
UPDATE factures SET telephone = '0498106787' WHERE LOWER(client) = LOWER('CES JEAN ROSTAND');
UPDATE factures SET email_client = 'azzedine.cftc@gmail.com' WHERE LOWER(client) = LOWER('CFTC RDT 13');
UPDATE factures SET telephone = '0699598034', email_client = 'l.bedrossiancftc@gmail.com' WHERE LOWER(client) = LOWER('CFTC/SNT CFE-CGC');
UPDATE factures SET telephone = '0645216797', email_client = 'Stephane.elmassian@cgd13.fr' WHERE LOWER(client) = LOWER('CGD13');
UPDATE factures SET telephone = '0651894821' WHERE LOWER(client) = LOWER('CHEZ MALIK');
UPDATE factures SET telephone = '0606775993' WHERE LOWER(client) = LOWER('CHICKEN BOUBOU');
UPDATE factures SET telephone = '0611544401' WHERE LOWER(client) = LOWER('CLC NET');
UPDATE factures SET telephone = '0491138461', email_client = 'marie-jose.giardina@entraide.asso.fr' WHERE LOWER(client) = LOWER('CLOS ST MARTIN');
UPDATE factures SET telephone = '0442307640', email_client = 'marine.silva@johncokerill.com' WHERE LOWER(client) = LOWER('CMI TECH PASTOR .');
UPDATE factures SET telephone = '0612756138' WHERE LOWER(client) = LOWER('COIFFEUR - STUDIO 13');
UPDATE factures SET telephone = '0666933957', email_client = 'comptabilite.fournisseurs@colisprive.com' WHERE LOWER(client) = LOWER('COLIS PRIVE');
UPDATE factures SET email_client = 'pierre.petit@compass-group.fr' WHERE LOWER(client) = LOWER('COMPASS GROUP COMPASS GROUP');
UPDATE factures SET telephone = '0617192337' WHERE LOWER(client) = LOWER('CONSEIL DEPARTEMENTAL DES B-D-R');
UPDATE factures SET telephone = '0442320439', email_client = 'joseph.jabes@gmail.com' WHERE LOWER(client) = LOWER('CONSEIL EXPERT .');
UPDATE factures SET email_client = 'pca@factures-meg.fr' WHERE LOWER(client) = LOWER('CONTROLE TECHNIQUE PIOLINE');
UPDATE factures SET telephone = '0662640141' WHERE LOWER(client) = LOWER('COURS D APPEL D AIX EN PROVENCE');
UPDATE factures SET telephone = '0491616955', email_client = 'Cynthia.sauvan@assurance-maladie.fr' WHERE LOWER(client) = LOWER('CPCAM');
UPDATE factures SET email_client = 'sandrine.gaillard@creap-etiquettes.fr' WHERE LOWER(client) = LOWER('CREAP');
UPDATE factures SET telephone = '0648194032' WHERE LOWER(client) = LOWER('CRYSTAL BARBER SHOP');
UPDATE factures SET telephone = '0670945652' WHERE LOWER(client) = LOWER('CUIR CENTER LA VALETTE DU VAR');
UPDATE factures SET telephone = '0491217766', email_client = 'corinne.imbert@technipenergies.com' WHERE LOWER(client) = LOWER('CYBERNETIX');
UPDATE factures SET telephone = '0623021137', email_client = 'contact@dancup.fr' WHERE LOWER(client) = LOWER('DANCUP SAS');
UPDATE factures SET telephone = '0624887192', email_client = 'mavagiu13@outlook.fr  ou  egypalsarl@gmail.com' WHERE LOWER(client) = LOWER('DE MERE EN FILLE BY NATHALIE');
UPDATE factures SET telephone = '0681656470', email_client = 'n.lepine@cuircenter.com' WHERE LOWER(client) = LOWER('DECO CENTER GRAND SUD');
UPDATE factures SET telephone = '0766899880', email_client = 'azzabi.aymen@gmail.com' WHERE LOWER(client) = LOWER('DELICE DU PORT');
UPDATE factures SET telephone = '0766471259', email_client = 'Malik01061983@gmail.com' WHERE LOWER(client) = LOWER('DELICE ORIENTAL');
UPDATE factures SET telephone = '0753395137' WHERE LOWER(client) = LOWER('DELICES DU BLED');
UPDATE factures SET email_client = 'comptabilite@deltascientifique.com' WHERE LOWER(client) = LOWER('DELTA SCIENTIFIQUE');
UPDATE factures SET email_client = 'yinizkaraslan@gmail.com' WHERE LOWER(client) = LOWER('DIYARBAKIR CITY');
UPDATE factures SET telephone = '0668827496', email_client = 'ichem.71@hotmail.fr' WHERE LOWER(client) = LOWER('DJILLYTEL');
UPDATE factures SET telephone = '0781373938' WHERE LOWER(client) = LOWER('DRUGSTORE');
UPDATE factures SET email_client = 'mapinto@marseille.fr' WHERE LOWER(client) = LOWER('Dion REGIE DES BATIMENTS');
UPDATE factures SET telephone = '0612182238', email_client = 'fmuller@stjomaristes.com' WHERE LOWER(client) = LOWER('ECOLE ST JOSEPH LES MARISTES');
UPDATE factures SET telephone = '0665575594' WHERE LOWER(client) = LOWER('EDEN PIZZA CREPES MARTIGUES');
UPDATE factures SET telephone = '0662777921', email_client = 'laurentspissu@gmail.com' WHERE LOWER(client) = LOWER('EI JOELLE SPISSU');
UPDATE factures SET telephone = '0676858900', email_client = 'patrick.contini@eiffage.fr' WHERE LOWER(client) = LOWER('EIFFAGE ENERGIE MEDITERRANEE-(FORCLUM)');
UPDATE factures SET telephone = '0491269909', email_client = 'xpalou@emd-management.fr' WHERE LOWER(client) = LOWER('EMD BUSINESS SCHOOL');
UPDATE factures SET telephone = '0442099899', email_client = 'facture.emmg@emmg.fr' WHERE LOWER(client) = LOWER('EMMG');
UPDATE factures SET telephone = '0658105770', email_client = 'empireautosmiramas@gmail.com' WHERE LOWER(client) = LOWER('EMPIRE AUTO MIRAMAS');
UPDATE factures SET telephone = '0768956463', email_client = 'f.alberti@hotmail.fr' WHERE LOWER(client) = LOWER('ENTRE TERRE ET MER');
UPDATE factures SET telephone = '0622586755' WHERE LOWER(client) = LOWER('ENTREPRISE GIRARD');
UPDATE factures SET telephone = '0491341398', email_client = 'espaceagoptical@gmail.com' WHERE LOWER(client) = LOWER('ESPACE OPTICAL');
UPDATE factures SET email_client = 'esvending@abv.bg' WHERE LOWER(client) = LOWER('ESPRESSO VENDING');
UPDATE factures SET telephone = '0658565293' WHERE LOWER(client) = LOWER('ESSI-SAPHIR (Nettoyage Merlan)');
UPDATE factures SET telephone = '0491434500' WHERE LOWER(client) = LOWER('ETS FERAUD');
UPDATE factures SET telephone = '0663226751', email_client = 'm.cabel@euridis.net' WHERE LOWER(client) = LOWER('EURIDIS');
UPDATE factures SET telephone = '0437233234' WHERE LOWER(client) = LOWER('F. TELECOM PYAT-ORANGE');
UPDATE factures SET telephone = '0491794718' WHERE LOWER(client) = LOWER('FEDERATION SUD EST COURSES HIPPIQUES');
UPDATE factures SET telephone = '0235883600', email_client = 'ssc-ptp-fr@ferrero.com' WHERE LOWER(client) = LOWER('FERRERO .');
UPDATE factures SET telephone = '0491174314', email_client = 'compta3.marseille@groupe-maurin.com' WHERE LOWER(client) = LOWER('FORD AUBAGNE');
UPDATE factures SET telephone = '0767111710' WHERE LOWER(client) = LOWER('FOURNIL DE FRAIS VALLON');
UPDATE factures SET telephone = '0491296430', email_client = 'marieastrid.uhring@sauvegarde13.org' WHERE LOWER(client) = LOWER('FOYER VERT PRE');
UPDATE factures SET telephone = '0632552689', email_client = 'edouard.lebosse@france-boissons.fr' WHERE LOWER(client) = LOWER('FRANCE BOISSONS');
UPDATE factures SET email_client = 'marseille@frigodepannage.com' WHERE LOWER(client) = LOWER('FRIGO DEPANNAGE');
UPDATE factures SET telephone = '0616421226', email_client = 'ftts@orange.fr' WHERE LOWER(client) = LOWER('FTTS');
UPDATE factures SET telephone = '0679570783', email_client = 'troig@marseille.fr' WHERE LOWER(client) = LOWER('FUNERARIUM ST PIERRE');
UPDATE factures SET telephone = '0622132701' WHERE LOWER(client) = LOWER('Fournil La Parisienne');
UPDATE factures SET telephone = '0492965572', email_client = 'x.barthelemy@roche-bobois.com' WHERE LOWER(client) = LOWER('G.I.E. SERVOGEST');
UPDATE factures SET telephone = '0622372266' WHERE LOWER(client) = LOWER('GALIX');
UPDATE factures SET email_client = 'contact@fiatdamar.fr' WHERE LOWER(client) = LOWER('GARAGE DAMAR');
UPDATE factures SET telephone = '0494004303', email_client = 'comptabilite@santalys-groupement.com' WHERE LOWER(client) = LOWER('GCS SANTALYS GROUPEMENT');
UPDATE factures SET telephone = '0491822312' WHERE LOWER(client) = LOWER('GEANT CASINO VALMANTE');
UPDATE factures SET telephone = '0611856013', email_client = 'gilles.laurent@gefco.fr' WHERE LOWER(client) = LOWER('GEFCO France SAS');
UPDATE factures SET telephone = '0609442335', email_client = 'grep4@orange.fr' WHERE LOWER(client) = LOWER('GEMENOS RUGBY EST PROVENCE');
UPDATE factures SET telephone = '0662850268', email_client = 'alexis.escorihuela@gendarmerie.defense.gouv.fr' WHERE LOWER(client) = LOWER('GENDARMERIE MARITIME');
UPDATE factures SET telephone = '0491371444' WHERE LOWER(client) = LOWER('GENERALE DISTRIBUTION');
UPDATE factures SET telephone = '0442913222', email_client = 'a.jehan@generim.com' WHERE LOWER(client) = LOWER('GENERIM2');
UPDATE factures SET telephone = '0651687571' WHERE LOWER(client) = LOWER('GEOEB');
UPDATE factures SET telephone = '0784907648', email_client = 'helline.guillem@groupeactual.eu' WHERE LOWER(client) = LOWER('GROUPE ACTUAL - MR SPORTICHE');
UPDATE factures SET telephone = '0636108581' WHERE LOWER(client) = LOWER('GROUPE MBS AIX 2');
UPDATE factures SET telephone = '0484326326' WHERE LOWER(client) = LOWER('GROUPE MBS La Valette');
UPDATE factures SET telephone = '0484326326', email_client = 'm.taieb@my-ambition.fr' WHERE LOWER(client) = LOWER('GROUPE MBS Marseille');
UPDATE factures SET telephone = '0649725725', email_client = 'minoterie@groupe-sos.org' WHERE LOWER(client) = LOWER('GROUPE SOS SOLIDARITE');
UPDATE factures SET telephone = '0758615710' WHERE LOWER(client) = LOWER('H BURGER');
UPDATE factures SET telephone = '0664399983' WHERE LOWER(client) = LOWER('HAGEN SPORT MANAGEMENT');
UPDATE factures SET telephone = '0612903568' WHERE LOWER(client) = LOWER('HAMMAM BY INES');
UPDATE factures SET telephone = '0646291193', email_client = 'sof.liberta@gmail.com' WHERE LOWER(client) = LOWER('HAMMAM SPA ZYAM');
UPDATE factures SET telephone = '0625091902' WHERE LOWER(client) = LOWER('HAT''S');
UPDATE factures SET telephone = '0498125052', email_client = 'seconomiques@ch-saint-tropez.fr' WHERE LOWER(client) = LOWER('HOPITAL ST TROPEZ GASSIN');
UPDATE factures SET telephone = '0601282736', email_client = 'eric.bindi@hopps-group.com' WHERE LOWER(client) = LOWER('HOPPS GROUP');
UPDATE factures SET telephone = '0778134601' WHERE LOWER(client) = LOWER('HOTEL DE REGION');
UPDATE factures SET telephone = '0626909465', email_client = 'laurence.delaigue@compass-group.fr' WHERE LOWER(client) = LOWER('HOTEL TERREBLANCHE RESORT');
UPDATE factures SET telephone = '0609742011', email_client = 'ibstransport@outlook.fr' WHERE LOWER(client) = LOWER('IBS TRANSPORT');
UPDATE factures SET telephone = '0645013155', email_client = 'veronique.couturier@ifptraining.com' WHERE LOWER(client) = LOWER('IFP TRAINING');
UPDATE factures SET telephone = '0491720400' WHERE LOWER(client) = LOWER('INGEROP');
UPDATE factures SET email_client = 'pascale.romanetti@cea.fr' WHERE LOWER(client) = LOWER('INSTN');
UPDATE factures SET telephone = '0687020763', email_client = 'servicesgeneraux@interway.fr' WHERE LOWER(client) = LOWER('INTERWAY');
UPDATE factures SET telephone = '0442176153' WHERE LOWER(client) = LOWER('ITER');
UPDATE factures SET telephone = '0612707550' WHERE LOWER(client) = LOWER('JEAN LOUIS PERRUCHON');
UPDATE factures SET telephone = '0660916383', email_client = 'c.floux@kissao.com' WHERE LOWER(client) = LOWER('KISSAO');
UPDATE factures SET telephone = '0601489017' WHERE LOWER(client) = LOWER('KIVANC FAMILY');
UPDATE factures SET email_client = 'cliclacphoto@hotmail.com' WHERE LOWER(client) = LOWER('KODAK EXPRESS');
UPDATE factures SET telephone = '0667778325' WHERE LOWER(client) = LOWER('L''ALBATROS');
UPDATE factures SET telephone = '0745374584' WHERE LOWER(client) = LOWER('L''OASIS DES FRUITS FRAIS');
UPDATE factures SET telephone = '0618547448' WHERE LOWER(client) = LOWER('LA BOULANGERIE D''AUTREFOIS');
UPDATE factures SET telephone = '0699994495' WHERE LOWER(client) = LOWER('LA BOULANGERIE DU CASTELLAS');
UPDATE factures SET telephone = '0660630745' WHERE LOWER(client) = LOWER('LA BOULE DES ARCADES');
UPDATE factures SET telephone = '0660313739' WHERE LOWER(client) = LOWER('LA COQUE');
UPDATE factures SET telephone = '0668931112' WHERE LOWER(client) = LOWER('LA FOURNEE DE PAGNOL');
UPDATE factures SET telephone = '0609807297' WHERE LOWER(client) = LOWER('LA FOURNEE DES MOLIERES');
UPDATE factures SET telephone = '0491609422', email_client = 'lapharmaciedesaygalades@gmail.com' WHERE LOWER(client) = LOWER('LA GRANDE PHARMACIE DES AYGALADES');
UPDATE factures SET telephone = '0601535260' WHERE LOWER(client) = LOWER('LA KASBAH DES HALLES');
UPDATE factures SET telephone = '0763690311' WHERE LOWER(client) = LOWER('LA MAISON COOKIES');
UPDATE factures SET telephone = '0615199094' WHERE LOWER(client) = LOWER('LA PAUSE CAFE EN OR');
UPDATE factures SET telephone = '0628520331', email_client = 'rcourbon@laprovence.com' WHERE LOWER(client) = LOWER('LA PROVENCE - LES NAUTICALES');
UPDATE factures SET telephone = '0638242594' WHERE LOWER(client) = LOWER('LA TABLE D''ALSACE');
UPDATE factures SET telephone = '0620580693', email_client = 'latabledanatolie@gmail.com' WHERE LOWER(client) = LOWER('LA TABLE D''ANATOLIE');
UPDATE factures SET telephone = '0673463473', email_client = 'menzeryacine@hotmail.fr' WHERE LOWER(client) = LOWER('LA TOUR DE PIZZ');
UPDATE factures SET email_client = 'ax-info@eurofins.com' WHERE LOWER(client) = LOWER('LABAZUR AIX (LABORATOIRE)');
UPDATE factures SET email_client = 'ax-info@eurofins.com' WHERE LOWER(client) = LOWER('LABAZUR AIX AUDE');
UPDATE factures SET telephone = '0442854035' WHERE LOWER(client) = LOWER('LABAZUR BERRE');
UPDATE factures SET telephone = '0787217079' WHERE LOWER(client) = LOWER('LABAZUR EUROFINS');
UPDATE factures SET email_client = 'ax-info@eurofins.com' WHERE LOWER(client) = LOWER('LABAZUR FUVEAU');
UPDATE factures SET telephone = '0442895589', email_client = 'ax-info@eurofins.com' WHERE LOWER(client) = LOWER('LABAZUR MARIGNANE 2');
UPDATE factures SET email_client = 'ax-info@eurofins.com' WHERE LOWER(client) = LOWER('LABAZUR PLAN CUQUES');
UPDATE factures SET telephone = '0442090709', email_client = 'ax-info@eurofins.com' WHERE LOWER(client) = LOWER('LABAZUR VILLE');
UPDATE factures SET telephone = '0491998900', email_client = 'direction.lacydon@entraide.asso.fr' WHERE LOWER(client) = LOWER('LACYDON');
UPDATE factures SET telephone = '0678650075' WHERE LOWER(client) = LOWER('LANAI CHRISTIAN');
UPDATE factures SET telephone = '0491104477' WHERE LOWER(client) = LOWER('LAPHAL INDUSTRIE');
UPDATE factures SET telephone = '0666394552', email_client = 'deltafeu@orange.fr' WHERE LOWER(client) = LOWER('LB INCENDIE');
UPDATE factures SET telephone = '0620036297', email_client = 'davidtenoudji@hotmail.fr' WHERE LOWER(client) = LOWER('LE CAMP MAJOR');
UPDATE factures SET email_client = 'lecoinderuffi@gmail.com' WHERE LOWER(client) = LOWER('LE COIN DE RUFFI');
UPDATE factures SET telephone = '0659512394' WHERE LOWER(client) = LOWER('LE DROMEL');
UPDATE factures SET telephone = '0663479686', email_client = 'be.formation69@gmail.com' WHERE LOWER(client) = LOWER('LE FORMATEC');
UPDATE factures SET telephone = '0641346671' WHERE LOWER(client) = LOWER('LE FOURNIL D''ALICE');
UPDATE factures SET telephone = '0659206845', email_client = 'karim.araifa@gmail.com' WHERE LOWER(client) = LOWER('LE FOURNIL DE MARTIGUES');
UPDATE factures SET telephone = '0659206845' WHERE LOWER(client) = LOWER('LE FOURNIL DE ROGNAC');
UPDATE factures SET telephone = '0667515961' WHERE LOWER(client) = LOWER('LE FOURNIL DE SALMA');
UPDATE factures SET telephone = '0651407565' WHERE LOWER(client) = LOWER('LE FOURNIL DES CHLOROPHYLLES');
UPDATE factures SET telephone = '0615380117' WHERE LOWER(client) = LOWER('LE FOURNIL DU 15 EME');
UPDATE factures SET telephone = '0663037664' WHERE LOWER(client) = LOWER('LE FOURNIL DU COIN');
UPDATE factures SET telephone = '0674316268' WHERE LOWER(client) = LOWER('LE FOURNIL DU MERLAN');
UPDATE factures SET telephone = '0699362626' WHERE LOWER(client) = LOWER('LE HAVANE');
UPDATE factures SET telephone = '0761818850', email_client = 'lepontetdestock@outlook.fr' WHERE LOWER(client) = LOWER('LE PONTET DESTOCK');
UPDATE factures SET telephone = '0686460272', email_client = 'lesalleesdesdelices@hotmail.fr' WHERE LOWER(client) = LOWER('LES ALLEES DES DELICES');
UPDATE factures SET telephone = '0661933570' WHERE LOWER(client) = LOWER('LES CABANES DU PORT');
UPDATE factures SET telephone = '0656805306', email_client = 'angyetenzo@gmail.com' WHERE LOWER(client) = LOWER('LES DELICES D AUBAGNE');
UPDATE factures SET telephone = '0609819581' WHERE LOWER(client) = LOWER('LES DOUCEURS DES CHARTREUX');
UPDATE factures SET telephone = '0610770966' WHERE LOWER(client) = LOWER('LISA FOURNIL');
UPDATE factures SET telephone = '0476200270', email_client = 'm.gutierez@bcaomnia.com' WHERE LOWER(client) = LOWER('LK INTERACTIVE');
UPDATE factures SET telephone = '0491760120', email_client = 'pr.lyc.daumier@ac-aix-marseille.fr' WHERE LOWER(client) = LOWER('LYCEE DAUMIER - AMICALE');
UPDATE factures SET telephone = '0647410247', email_client = 'fred.fourniller@laposte.net' WHERE LOWER(client) = LOWER('LYCEE DIDEROT');
UPDATE factures SET telephone = '0629926676' WHERE LOWER(client) = LOWER('MAHFOUD');
UPDATE factures SET telephone = '0622392292', email_client = 'skoska@marseille.fr' WHERE LOWER(client) = LOWER('MAIRIE 13-14');
UPDATE factures SET telephone = '0615675114', email_client = 'nathalie.duclap@aubagne.fr' WHERE LOWER(client) = LOWER('MAIRIE AUBAGNE');
UPDATE factures SET telephone = '0632871563' WHERE LOWER(client) = LOWER('MAIRIE HOTEL DE VILLE');
UPDATE factures SET telephone = '0632871563', email_client = 'lsalvador@marseille.fr>' WHERE LOWER(client) = LOWER('MAIRIE du 2ème');
UPDATE factures SET telephone = '0699200502' WHERE LOWER(client) = LOWER('MAISON DE LA REGION DU VAR');
UPDATE factures SET telephone = '0681563519', email_client = 'contact@maisonmonsieurlouis.com' WHERE LOWER(client) = LOWER('MAISON MONSIEUR LOUIS');
UPDATE factures SET telephone = '0442511844', email_client = 'grenier.bruno@notaires.fr' WHERE LOWER(client) = LOWER('MAITRE GRENIER BRUNO');
UPDATE factures SET telephone = '0783030326' WHERE LOWER(client) = LOWER('MAJID Fruits et Légumes');
UPDATE factures SET telephone = '0617658294', email_client = 'compta@manhattanhotdog.com' WHERE LOWER(client) = LOWER('MANHATTAN HOT DOG');
UPDATE factures SET telephone = '0618240965' WHERE LOWER(client) = LOWER('MARCHE DE LA LITERIE');
UPDATE factures SET email_client = 'www.marsfrance.fr' WHERE LOWER(client) = LOWER('MARS WRIGLEY CONFECTIONERY');
UPDATE factures SET telephone = '0491048282', email_client = 'jacqueline.garnier@rmm-co.com' WHERE LOWER(client) = LOWER('MARTIN MAUREL .');
UPDATE factures SET telephone = '0491448250', email_client = 'marie-jose.giardina@entraide.asso.fr' WHERE LOWER(client) = LOWER('MDR LE MARYLISE');
UPDATE factures SET telephone = '0491418043', email_client = 'direction.les-pins@entraide.asso.fr' WHERE LOWER(client) = LOWER('MDR RESIDENCE LES PINS');
UPDATE factures SET telephone = '0652401136', email_client = 'ANTEN13-69@hotmail.fr' WHERE LOWER(client) = LOWER('MELANA');
UPDATE factures SET telephone = '0643786409' WHERE LOWER(client) = LOWER('MIKAIL CLAUDE');
UPDATE factures SET telephone = '0674054487', email_client = 'hamidiy@hotmail.fr' WHERE LOWER(client) = LOWER('MIMOSAS');
UPDATE factures SET telephone = '0772046237', email_client = 'comptabilite@trust-industrie.fr' WHERE LOWER(client) = LOWER('MOBILIER MALIN');
UPDATE factures SET email_client = 'monsieurmeuble.avignon@orange.fr' WHERE LOWER(client) = LOWER('MONSIEUR MEUBLE');
UPDATE factures SET telephone = '0684513548' WHERE LOWER(client) = LOWER('MONSIEUR TEYSSIER BERNARD');
UPDATE factures SET telephone = '0767732822', email_client = 'contact@msa-environnement.fr' WHERE LOWER(client) = LOWER('MSA ENVIRONNEMENT');
UPDATE factures SET email_client = 'contact@mvagusta-marseille.fr' WHERE LOWER(client) = LOWER('MV STORE - SUR RON');
UPDATE factures SET email_client = 'm.taieb@my-ambition.fr' WHERE LOWER(client) = LOWER('MY FASHION SCHOOL');
UPDATE factures SET telephone = '0491616263', email_client = 'secretariat.sln@residalya.com' WHERE LOWER(client) = LOWER('Maison Retraite Les Séolanes');
UPDATE factures SET telephone = '0491237500', email_client = 'dir-marseille-saint-barnabe@dolcea.fr' WHERE LOWER(client) = LOWER('Maison Retraite Saint Barnabé');
UPDATE factures SET telephone = '0442592637', email_client = 'daniel.dubuis@entraide.asso.fr' WHERE LOWER(client) = LOWER('Maison de Retraite LOU PARADOU');
UPDATE factures SET telephone = '0787456543' WHERE LOWER(client) = LOWER('NARGUI LOUNGE');
UPDATE factures SET telephone = '0699799189', email_client = 'omanai13560@gmail.com' WHERE LOWER(client) = LOWER('O''MANAI SENAS');
UPDATE factures SET telephone = '0761665926', email_client = 'BDP13002@gmail .com' WHERE LOWER(client) = LOWER('OCCAZ LOC');
UPDATE factures SET telephone = '0637176992', email_client = 'christophe.caldeirinha@suntory.com' WHERE LOWER(client) = LOWER('ORANGINA  SCHWEPPES FRANCE');
UPDATE factures SET telephone = '0665504105', email_client = 'spanivello@orpi.com' WHERE LOWER(client) = LOWER('ORPI IMH');
UPDATE factures SET telephone = '0636734970' WHERE LOWER(client) = LOWER('PAPENCO');
UPDATE factures SET telephone = '0627557840' WHERE LOWER(client) = LOWER('PASINO (CASINO) - C.E.');
UPDATE factures SET telephone = '0609339343', email_client = 'hatslogistique@gmail.com' WHERE LOWER(client) = LOWER('PEPE CAFE');
UPDATE factures SET telephone = '0788639101' WHERE LOWER(client) = LOWER('PER POTER');
UPDATE factures SET telephone = '0605688533' WHERE LOWER(client) = LOWER('PERGOLA TRADING');
UPDATE factures SET email_client = 'sophie.dalessandro@perrenot.eu' WHERE LOWER(client) = LOWER('PERRENOT FOS');
UPDATE factures SET telephone = '0625862950', email_client = 'levetti.audrey@orange.fr' WHERE LOWER(client) = LOWER('PETRIN DE FAMILLE BOULANGERIE');
UPDATE factures SET telephone = '0442353133', email_client = 'jean-christophe.boillot@petroineos.fr' WHERE LOWER(client) = LOWER('PETROINEOS');
UPDATE factures SET telephone = '0491795493', email_client = 'pharmaciedelatour13@gmail.com' WHERE LOWER(client) = LOWER('PHARMACIE DE LA TOUR');
UPDATE factures SET telephone = '0491654230', email_client = 'pharmaciedubosphore@gmail.com' WHERE LOWER(client) = LOWER('PHARMACIE DU BOSPHORE');
UPDATE factures SET telephone = '0782299985' WHERE LOWER(client) = LOWER('PHONE CENTER');
UPDATE factures SET telephone = '0662333232' WHERE LOWER(client) = LOWER('PIGIER');
UPDATE factures SET telephone = '0618077353' WHERE LOWER(client) = LOWER('PINOCCHIO');
UPDATE factures SET telephone = '0660557863' WHERE LOWER(client) = LOWER('PLAISIR DU PAIN');
UPDATE factures SET telephone = '0612767550', email_client = 'abellasandrina@gmail.com' WHERE LOWER(client) = LOWER('POLE MED SPORT INSTITUTE');
UPDATE factures SET telephone = '0624314013' WHERE LOWER(client) = LOWER('POMPIERS ST TROPEZ');
UPDATE factures SET telephone = '0765772054' WHERE LOWER(client) = LOWER('POOL HALL');
UPDATE factures SET telephone = '0494680554', email_client = 'jean.chiofalo@laposte.fr' WHERE LOWER(client) = LOWER('POSTE  TRI GRIMAUD');
UPDATE factures SET telephone = '0498104262', email_client = 'malika.guellati@laposte.fr' WHERE LOWER(client) = LOWER('POSTE DRAGUIGNAN');
UPDATE factures SET telephone = '0494188410', email_client = 'sophie.beranger@var.gouv.fr' WHERE LOWER(client) = LOWER('PREFECTURE DU VAR');
UPDATE factures SET telephone = '0658637821' WHERE LOWER(client) = LOWER('PSI');
UPDATE factures SET telephone = '0491750451' WHERE LOWER(client) = LOWER('Perrin Fabienne');
UPDATE factures SET telephone = '0619662659' WHERE LOWER(client) = LOWER('QUATRE SAISONS');
UPDATE factures SET telephone = '0622673018' WHERE LOWER(client) = LOWER('QUINCAILLERIE DU LITTORAL');
UPDATE factures SET telephone = '0494038756' WHERE LOWER(client) = LOWER('RESEAU MISTRAL');
UPDATE factures SET telephone = '0490969095', email_client = 'direction.griffeuille@entraide.asso.fr' WHERE LOWER(client) = LOWER('RESIDENCE GRIFEUILLE');
UPDATE factures SET telephone = '0764885955', email_client = 'caroline.penther@univi.fr' WHERE LOWER(client) = LOWER('RESIDENCE LE BELVEDERE');
UPDATE factures SET email_client = 'marie-jose.giardina@entraide.asso.fr' WHERE LOWER(client) = LOWER('RESIDENCE LE MAS DE SARRET');
UPDATE factures SET telephone = '0491138400', email_client = 'marie-jose@giardina@entraide.asso.fr' WHERE LOWER(client) = LOWER('RESIDENCE LE ROY D''ESPAGNE');
UPDATE factures SET telephone = '0442663137', email_client = 'marie-jose.giardina@entraide.asso.fr' WHERE LOWER(client) = LOWER('RESIDENCE LENSOULEIADO');
UPDATE factures SET email_client = 'marie-jose.giardina@entraide.asso.fr' WHERE LOWER(client) = LOWER('RESIDENCE LES JARDIN FLEURIS');
UPDATE factures SET telephone = '0442106800', email_client = 'direction.lesoliviers@entraide.asso.fr' WHERE LOWER(client) = LOWER('RESIDENCE OLIVIERS DE ST JEAN');
UPDATE factures SET telephone = '0624864925' WHERE LOWER(client) = LOWER('RESTAURANT L''HEMISPHERE');
UPDATE factures SET telephone = '0672508726', email_client = 'eurlronysemaan@gmail.com' WHERE LOWER(client) = LOWER('RESTAURANT LE CEDRE');
UPDATE factures SET telephone = '0683714801', email_client = 'kachetel.femina@hotmail.fr' WHERE LOWER(client) = LOWER('RESTAURANT LE FEMINA');
UPDATE factures SET telephone = '0442343410', email_client = 's.courrier@roche-bobois.com' WHERE LOWER(client) = LOWER('ROCHE BOBOIS');
UPDATE factures SET email_client = 's.courrier@roche-bobois.com' WHERE LOWER(client) = LOWER('ROCHE BOBOIS MARSEILLE');
UPDATE factures SET telephone = '0771698737', email_client = 'sutka-79@hotmail.fr' WHERE LOWER(client) = LOWER('SARAY GRILL');
UPDATE factures SET telephone = '0659605382', email_client = 'agrodis84130@gmail.com' WHERE LOWER(client) = LOWER('SARL ABO');
UPDATE factures SET telephone = '0625190249' WHERE LOWER(client) = LOWER('SARL ATLANTIQUE');
UPDATE factures SET telephone = '0490955900', email_client = 'deurrieu.freres@orange.fr' WHERE LOWER(client) = LOWER('SARL DEURRIEU');
UPDATE factures SET telephone = '0684993917', email_client = 'romainmisraki@gmail.com' WHERE LOWER(client) = LOWER('SARL FELICE');
UPDATE factures SET telephone = '0766029603' WHERE LOWER(client) = LOWER('SARL FINDIK');
UPDATE factures SET telephone = '0634545837', email_client = 'fmaghni@efirec.fr' WHERE LOWER(client) = LOWER('SARL K ET F FOOD (SMOKE MEAT)');
UPDATE factures SET telephone = '0628380460', email_client = 'vl@secogefi.fr' WHERE LOWER(client) = LOWER('SARL LA CORNE DE GAZELLE');
UPDATE factures SET telephone = '0674308557' WHERE LOWER(client) = LOWER('SARL LA RENAISSANCE');
UPDATE factures SET telephone = '0616818069', email_client = 'amelamari1982@gmail.com' WHERE LOWER(client) = LOWER('SARL NOSIA');
UPDATE factures SET telephone = '0650504614', email_client = 'cdc7lacledeschamps@gmail.com' WHERE LOWER(client) = LOWER('SARL SAHA');
UPDATE factures SET telephone = '0651556753', email_client = 'lindinia@live.fr' WHERE LOWER(client) = LOWER('SAS ADAILY');
UPDATE factures SET telephone = '0624255493', email_client = 'amsbtp84@gmail.com' WHERE LOWER(client) = LOWER('SAS AMS BTP');
UPDATE factures SET telephone = '0745374584' WHERE LOWER(client) = LOWER('SAS AU PAIN D''AUTREFOIS');
UPDATE factures SET telephone = '0490955900' WHERE LOWER(client) = LOWER('SAS BARBEN INTERMARCHE');
UPDATE factures SET telephone = '0666032751' WHERE LOWER(client) = LOWER('SAS CARTHAGE');
UPDATE factures SET telephone = '0625817645' WHERE LOWER(client) = LOWER('SAS CHELAOUI');
UPDATE factures SET telephone = '0491701708' WHERE LOWER(client) = LOWER('SAS FOURNIL DES OLIVES');
UPDATE factures SET email_client = 'yoannfernandez13@gmail.com' WHERE LOWER(client) = LOWER('SAS Fernandez et fils');
UPDATE factures SET telephone = '0609972766' WHERE LOWER(client) = LOWER('SAS HOTEL ST JEAN');
UPDATE factures SET telephone = '0640546425' WHERE LOWER(client) = LOWER('SAS JYMH');
UPDATE factures SET telephone = '0619578329', email_client = 'menoone@hotmail.fr' WHERE LOWER(client) = LOWER('SAS LE BLE D''OR');
UPDATE factures SET telephone = '0762706898' WHERE LOWER(client) = LOWER('SAS LE VOYAGE');
UPDATE factures SET telephone = '0674054487' WHERE LOWER(client) = LOWER('SAS MARJANE');
UPDATE factures SET telephone = '0634870557', email_client = 'lamimpdor@dext.cc' WHERE LOWER(client) = LOWER('SAS MIMP D''OR');
UPDATE factures SET telephone = '0678721389', email_client = 'joy.dufour@workandevent.fr' WHERE LOWER(client) = LOWER('SAS NADENOEN');
UPDATE factures SET telephone = '0765254555', email_client = 'bounouaahmed@yahoo.fr' WHERE LOWER(client) = LOWER('SAS NEW ALCAZAR');
UPDATE factures SET telephone = '0616998799' WHERE LOWER(client) = LOWER('SAS SAFA (BOULANGERIE FERRIERES)');
UPDATE factures SET telephone = '0674352103', email_client = 'icdr13@gmail.com' WHERE LOWER(client) = LOWER('SAS SAN CARLO');
UPDATE factures SET telephone = '0674054487', email_client = 'tacosnburger@hotmail.com' WHERE LOWER(client) = LOWER('SAS SNACK DU THEATRE');
UPDATE factures SET telephone = '0674352103' WHERE LOWER(client) = LOWER('SAS Salerno');
UPDATE factures SET telephone = '0686460272', email_client = 'leboulevarddesdelices@hotmail.com' WHERE LOWER(client) = LOWER('SASU ALCAMO');
UPDATE factures SET telephone = '0780558299' WHERE LOWER(client) = LOWER('SASU BEYZADE');
UPDATE factures SET telephone = '0491740385', email_client = 'michele.mira@sauvegarde13.org' WHERE LOWER(client) = LOWER('SAUVEGARDE 13 SIEGE');
UPDATE factures SET telephone = '0442257105', email_client = 'sbvme-ac@cea.fr' WHERE LOWER(client) = LOWER('SBVME');
UPDATE factures SET telephone = '0648157502' WHERE LOWER(client) = LOWER('SELMAC EXPLOITATION');
UPDATE factures SET telephone = '0646836368' WHERE LOWER(client) = LOWER('SERVICE POMPES FUNEBRES 05');
UPDATE factures SET telephone = '0637925183' WHERE LOWER(client) = LOWER('SG AU BON GOUT');
UPDATE factures SET telephone = '0786384262', email_client = 'p.trassoudaine@groupenicollin.com' WHERE LOWER(client) = LOWER('SMN');
UPDATE factures SET telephone = '0683968410', email_client = 'asarlin@smri-sa.com' WHERE LOWER(client) = LOWER('SMRI ATEX');
UPDATE factures SET telephone = '0767710432' WHERE LOWER(client) = LOWER('SNACK BACHIR');
UPDATE factures SET telephone = '0619776356' WHERE LOWER(client) = LOWER('SNACK BOLO');
UPDATE factures SET telephone = '0780884425' WHERE LOWER(client) = LOWER('SNACK DU CENTRE');
UPDATE factures SET telephone = '0774645489' WHERE LOWER(client) = LOWER('SNACK FLORIDA PARK');
UPDATE factures SET telephone = '0652488106' WHERE LOWER(client) = LOWER('SNACK HANANE');
UPDATE factures SET telephone = '0666785024' WHERE LOWER(client) = LOWER('SNACK LA BIENVENUE');
UPDATE factures SET telephone = '0495040769' WHERE LOWER(client) = LOWER('SNCF CPR SERVICES GENERAUX');
UPDATE factures SET telephone = '0745739321', email_client = 'sotacos84@gmail.com' WHERE LOWER(client) = LOWER('SO TACOS');
UPDATE factures SET telephone = '0617491635', email_client = 'silvio.iacovino@sofitel.com' WHERE LOWER(client) = LOWER('SOFITEL');
UPDATE factures SET email_client = 'solution.confort13@gmail.com' WHERE LOWER(client) = LOWER('SOLUTIONS CONFORT CVC');
UPDATE factures SET telephone = '0613084393', email_client = 'sovelleron@gmail.com' WHERE LOWER(client) = LOWER('SPORT OLYMPIQUE VELLERONNAIS');
UPDATE factures SET telephone = '0632871040' WHERE LOWER(client) = LOWER('STADE NAUTIQUE SARTHAUD');
UPDATE factures SET telephone = '0442981390', email_client = 'vblondel@euros.fr' WHERE LOWER(client) = LOWER('STE EUROS');
UPDATE factures SET email_client = 'thierry.gagliano@hippodromesmarseille.fr' WHERE LOWER(client) = LOWER('STE HIPPIQUE DE MARSEILLE');
UPDATE factures SET telephone = '0651324592', email_client = 'aziza.hbabou@stef.com' WHERE LOWER(client) = LOWER('STEF');
UPDATE factures SET telephone = '0615435240', email_client = 'salatretsoise@wanadoo.fr' WHERE LOWER(client) = LOWER('STEFANELLI BOUCHERIE');
UPDATE factures SET telephone = '0619507257' WHERE LOWER(client) = LOWER('SUD PRIMEURS');
UPDATE factures SET telephone = '0758843078' WHERE LOWER(client) = LOWER('SUPERETTE DE FRAIS VALLON');
UPDATE factures SET telephone = '0481761736', email_client = 'kmadi@systra.com' WHERE LOWER(client) = LOWER('SYSTRA .');
UPDATE factures SET telephone = '0669179020', email_client = 'tabacdesmartegaux@yahoo.com' WHERE LOWER(client) = LOWER('TABAC DES MARTEGAUX');
UPDATE factures SET telephone = '0620036297', email_client = 'tabaclecampmajor@outlook.fr' WHERE LOWER(client) = LOWER('TABAC LE CAMP MAJOR');
UPDATE factures SET telephone = '0620397797' WHERE LOWER(client) = LOWER('TEAM KUCH AUTO');
UPDATE factures SET telephone = '0780912689', email_client = 'the-oz.com' WHERE LOWER(client) = LOWER('THE OZ');
UPDATE factures SET telephone = '0496178008', email_client = 'a.madelin@theatre-lacriee.com' WHERE LOWER(client) = LOWER('THEATRE LA CRIEE');
UPDATE factures SET email_client = 'tnautopneus13@gmail.com' WHERE LOWER(client) = LOWER('TN AUTOS PNEUS');
UPDATE factures SET telephone = '0641124383' WHERE LOWER(client) = LOWER('TRADING NEGOCE');
UPDATE factures SET email_client = 'diane.compta@transportsmariani.fr' WHERE LOWER(client) = LOWER('TRANSPORT MARIANI');
UPDATE factures SET telephone = '0613540295', email_client = 'tarik.laateur@vinci-construction.fr' WHERE LOWER(client) = LOWER('TRAVAUX DU MIDI- VINCI');
UPDATE factures SET telephone = '0680168373', email_client = 'comptabilite@trust-industrie.fr' WHERE LOWER(client) = LOWER('TRUST MOBILIER 78');
UPDATE factures SET telephone = '0662640141', email_client = 'candice.guissart@justice.fr' WHERE LOWER(client) = LOWER('Tribunal Judiciaire');
UPDATE factures SET telephone = '0763605282', email_client = 'p.clot@unapei-ap.fr' WHERE LOWER(client) = LOWER('UNAPEI ESAT LES BAMBOUS');
UPDATE factures SET telephone = '0658557192', email_client = 'c.boi@unapei-ap.fr' WHERE LOWER(client) = LOWER('UNAPEI FOYER EXISTE');
UPDATE factures SET telephone = '0603753226', email_client = 'c.gadenne@unapei-ap.fr' WHERE LOWER(client) = LOWER('UNAPEI LES GLYCINES');
UPDATE factures SET telephone = '0491095660', email_client = 'm.lebon@unapei-ap.fr' WHERE LOWER(client) = LOWER('UNAPEI LES LIERRES');
UPDATE factures SET telephone = '0647544155', email_client = 'j.sartini@unapei-ap.fr' WHERE LOWER(client) = LOWER('UNAPEI LES LILAS');
UPDATE factures SET email_client = 'c.julia@unapei-ap.fr' WHERE LOWER(client) = LOWER('UNAPEI SIEGE CHRYSALIDE');
UPDATE factures SET telephone = '0772772410', email_client = 'uniprim@free.fr' WHERE LOWER(client) = LOWER('UNIPRIM');
UPDATE factures SET telephone = '0664330371', email_client = 'stephanecrespin@neuf.fr' WHERE LOWER(client) = LOWER('UNSA CHEMINOTS PACA');
UPDATE factures SET telephone = '0633471029', email_client = 'accueil@cfdt-paca.fr' WHERE LOWER(client) = LOWER('URI CFTD');
UPDATE factures SET telephone = '0764855030', email_client = 'vartan9@hotmail.fr' WHERE LOWER(client) = LOWER('VARTAN OHANIAN');
UPDATE factures SET telephone = '0626250146' WHERE LOWER(client) = LOWER('VIA NAPOLI 19');
UPDATE factures SET telephone = '0442016918', email_client = 'sandra.sasselli.13034@notaires.fr' WHERE LOWER(client) = LOWER('VIDAL .');
UPDATE factures SET telephone = '0632289191', email_client = 'nbeltrand@marseille.fr' WHERE LOWER(client) = LOWER('VILLE DE MARSEILLE Service logistique informatique');
UPDATE factures SET telephone = '0612771547', email_client = 'Samir.taieba@vinci-construction.fr' WHERE LOWER(client) = LOWER('VINCI VILLA PRINTEMPS');
UPDATE factures SET telephone = '0987755060' WHERE LOWER(client) = LOWER('VISAGE DU SUD');
UPDATE factures SET telephone = '0767537243' WHERE LOWER(client) = LOWER('ZAZA DESIGN');

-- Total : 359 entreprises avec au moins un contact